spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db.changelog-master.xml